### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by cmhungsteve** [liuyang-ict/awesome-visual-transformers#1]
Thank you for sharing this collection of papers

I also made a paper collection list about vision attention and transformer:
https://github.com/cmhungsteve/Awesome-Transformer-Attention

Feel free to check and share it!

I will also be appreciative if you can add a link to my repo.
Thank you

**Comment by liuyang-ict** [comment]
ok, I will update the URL soon.

**Comment by liuyang-ict** [comment]
The URL is updated. Any other comments, please feel free to contact me~
By the way, the survey has been published in TNNLS, please update the source of this paper in your repo.

Thanks

**Comment by cmhungsteve** [comment]
updated. Thank you for the reminder
